CAREER_QUIZZES = {
    "Software Developer": [
        {"question": "Which data structure uses LIFO (Last In First Out) order?", "options": ["Queue", "Stack", "Array", "Linked List"], "answer": "Stack", "explanation": "A Stack follows the LIFO principle."},
        {"question": "What does API stand for?", "options": ["Application Programming Interface", "Advanced Program Integration", "Automated Process Interaction", "Application Process Interface"], "answer": "Application Programming Interface", "explanation": "API allows different software to communicate."},
        {"question": "In Object-Oriented Programming, what is 'Inheritance'?", "options": ["Hiding data", "Creating new classes from existing ones", "Polymorphism", "Encapsulation"], "answer": "Creating new classes from existing ones", "explanation": "Inheritance allows a class to derive properties from another class."},
        {"question": "Which of these is a relational database management system?", "options": ["MongoDB", "Redis", "MySQL", "Neo4j"], "answer": "MySQL", "explanation": "MySQL is a popular RDBMS based on SQL."},
        {"question": "What is the time complexity of binary search?", "options": ["O(n)", "O(n^2)", "O(log n)", "O(1)"], "answer": "O(log n)", "explanation": "Binary search divides the search interval in half."},
        {"question": "Which protocol is primarily used for loading web pages?", "options": ["FTP", "SMTP", "HTTP", "SSH"], "answer": "HTTP", "explanation": "HTTP (Hypertext Transfer Protocol) is the foundation of data communication for the WWW."},
        {"question": "What does a 'commits' refer to in Git?", "options": ["Deleting code", "Saving changes to the repository", "Running code", "Testing code"], "answer": "Saving changes to the repository", "explanation": "A commit records changes to the repository."},
        {"question": "Which language is known as the 'mother of all languages'?", "options": ["Python", "Java", "C", "Assembly"], "answer": "C", "explanation": "C influenced many modern languages like C++, Java, and Python."},
        {"question": "What is 'Cloud Computing'?", "options": ["Computing on local servers", "Delivery of computing services over the internet", "Weather forecasting", "Using supercomputers"], "answer": "Delivery of computing services over the internet", "explanation": "It offers servers, storage, and databases over the web."},
        {"question": "What is a 'Bug' in software?", "options": ["A feature", "An error or flaw", "A virus", "A user"], "answer": "An error or flaw", "explanation": "A bug causes software to produce incorrect or unexpected results."}
    ],
    "Doctor": [
        {"question": "Which organ pumps blood throughout the human body?", "options": ["Lungs", "Brain", "Heart", "Liver"], "answer": "Heart", "explanation": "The heart pumps blood through the circulatory system."},
        {"question": "What is the normal human body temperature?", "options": ["35°C", "37°C", "40°C", "32°C"], "answer": "37°C", "explanation": "Normal body temperature is approximately 37°C (98.6°F)."},
        {"question": "Which part of the blood helps in clotting?", "options": ["Red Blood Cells", "White Blood Cells", "Plasma", "Platelets"], "answer": "Platelets", "explanation": "Platelets form clots to stop bleeding."},
        {"question": "What is the study of tissues called?", "options": ["Histology", "Cytology", "Anatomy", "Pathology"], "answer": "Histology", "explanation": "Histology is the microscopic study of tissues."},
        {"question": "Which vitamin is produced when skin is exposed to sunlight?", "options": ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], "answer": "Vitamin D", "explanation": "Sunlight triggers Vitamin D synthesis in the skin."},
        {"question": "What is the largest organ in the human body?", "options": ["Liver", "Connective Tissue", "Skin", "Femur"], "answer": "Skin", "explanation": "The skin is the largest organ, covering the entire body."},
        {"question": "Which specialist treats heart diseases?", "options": ["Neurologist", "Cardiologist", "Dermatologist", "Pediatrician"], "answer": "Cardiologist", "explanation": "Cardiologists specialize in the heart and blood vessels."},
        {"question": "What does MRI stand for?", "options": ["Magnetic Resonance Imaging", "Medical Research Imaging", "Magnetic Ray Indicator", "Medical Resonance Indicator"], "answer": "Magnetic Resonance Imaging", "explanation": "MRI uses magnets and radio waves to create body images."},
        {"question": "Which gas is primarily inhaled during respiration?", "options": ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"], "answer": "Oxygen", "explanation": "Humans inhale oxygen and exhale carbon dioxide."},
        {"question": "What is 'Anemia' caused by?", "options": ["Lack of Calcium", "Lack of Iron", "Lack of Protein", "Lack of Sleep"], "answer": "Lack of Iron", "explanation": "Iron deficiency leads to reduced hemoglobin and anemia."}
    ],
    "Data Scientist": [
        {"question": "Which library is standard for data manipulation in Python?", "options": ["NumPy", "Pandas", "Matplotlib", "Seaborn"], "answer": "Pandas", "explanation": "Pandas provides data structures like DataFrames for manipulation."},
        {"question": "What is 'Supervised Learning'?", "options": ["Learning without data", "Training on labeled data", "Training on unlabeled data", "Self-learning"], "answer": "Training on labeled data", "explanation": "The model learns from input-output pairs."},
        {"question": "Which plot is best for showing distribution?", "options": ["Scatter Plot", "Pie Chart", "Histogram", "Line Chart"], "answer": "Histogram", "explanation": "Histograms visualize the frequency distribution of continuous data."},
        {"question": "What does a correlation of -1 indicate?", "options": ["No relation", "Strong positive relation", "Strong negative relation", "Weak relation"], "answer": "Strong negative relation", "explanation": "-1 indicates a perfect inverse relationship."},
        {"question": "What is 'Overfitting'?", "options": ["Model performs well on training and test data", "Model learns noise instead of pattern", "Model is too simple", "Model fits under the curve"], "answer": "Model learns noise instead of pattern", "explanation": "Overfitting happens when a model fits training data too closely."},
        {"question": "Which algorithm is used for classification?", "options": ["Linear Regression", "K-Means", "Decision Tree", "PCA"], "answer": "Decision Tree", "explanation": "Decision Trees work for both classification and regression."},
        {"question": "What does 'SQL' stand for?", "options": ["Structured Query Language", "Simple Query Language", "Standard Question List", "System Query Logic"], "answer": "Structured Query Language", "explanation": "SQL is used for managing relational databases."},
        {"question": "What is 'Data Cleaning'?", "options": ["Deleting data", "Formatting code", "Fixing errors/missing values in data", "Securing data"], "answer": "Fixing errors/missing values in data", "explanation": "It involves preparing raw data for analysis."},
        {"question": "Which of these is a measure of central tendency?", "options": ["Variance", "Standard Deviation", "Median", "Range"], "answer": "Median", "explanation": "Mean, Median, and Mode are measures of central tendency."},
        {"question": "What is a 'Neural Network' inspired by?", "options": ["Computer circuits", "Human brain", "Solar system", "Ant colonies"], "answer": "Human brain", "explanation": "Neural networks mimic the structure of biological neurons."}
    ],
    "Architect": [
        {"question": "What is the primary tool for architectural drafting?", "options": ["CAD", "Photoshop", "Excel", "Word"], "answer": "CAD", "explanation": "Computer-Aided Design (CAD) is standard for drafting."},
        {"question": "What is a 'Blueprint'?", "options": ["A business plan", "A technical drawing of a building", "A painting", "A legal document"], "answer": "A technical drawing of a building", "explanation": "Blueprints show the design and layout of a structure."},
        {"question": "Which famous architect designed the Guggenheim Museum?", "options": ["Frank Lloyd Wright", "Zaha Hadid", "Le Corbusier", "Norman Foster"], "answer": "Frank Lloyd Wright", "explanation": "He is a pioneer of modern architecture."},
        {"question": "What does 'Sustainability' in architecture focus on?", "options": ["Making buildings tall", "Using eco-friendly materials and energy", "Using expensive materials", "Speed of construction"], "answer": "Using eco-friendly materials and energy", "explanation": "It aims to minimize environmental impact."},
        {"question": "What is a 'Facade'?", "options": ["The roof", "The foundation", "The exterior face of a building", "The interior wall"], "answer": "The exterior face of a building", "explanation": "The facade is usually the front or main exterior side."},
        {"question": "Which material is known for high compressive strength?", "options": ["Wood", "Concrete", "Glass", "Plastic"], "answer": "Concrete", "explanation": "Concrete is excellent at resisting compression."},
        {"question": "What is 'Urban Planning'?", "options": ["Designing furniture", "Designing cities and communities", "Painting buildings", "Gardening"], "answer": "Designing cities and communities", "explanation": "It involves land use and infrastructure planning."},
        {"question": "The 'Keystone' is part of which structure?", "options": ["Arch", "Column", "Beam", "Slab"], "answer": "Arch", "explanation": "The keystone locks the arch stones in place."},
        {"question": "What is 'Ergonomics'?", "options": ["Study of rocks", "Design for human efficiency and comfort", "Study of economy", "Structural analysis"], "answer": "Design for human efficiency and comfort", "explanation": "Ensures spaces fit human needs."},
        {"question": "Who famously said 'Form follows function'?", "options": ["Louis Sullivan", "Frank Gehry", "Michelangelo", "Da Vinci"], "answer": "Louis Sullivan", "explanation": "A principle of modern architecture."}
    ],
    "Graphic Designer": [
        {"question": "Which color mode is used for printing?", "options": ["RGB", "CMYK", "HEX", "HSL"], "answer": "CMYK", "explanation": "Cyan, Magenta, Yellow, Key (Black) is for print."},
        {"question": "What is 'Typography'?", "options": ["Mapping", "Art of arranging type/text", "Typing speed", "Printing press"], "answer": "Art of arranging type/text", "explanation": "Typography involves font choice and layout."},
        {"question": "Which file format supports transparency?", "options": ["JPG", "PNG", "TXT", "MP4"], "answer": "PNG", "explanation": "PNG supports alpha channels for transparency."},
        {"question": "What does 'UI' stand for?", "options": ["User Interaction", "User Interface", "Unified Image", "Under Interface"], "answer": "User Interface", "explanation": "UI refers to the visual elements a user interacts with."},
        {"question": "Which tool is best for vector graphics?", "options": ["Photoshop", "Illustrator", "Premiere Pro", "Excel"], "answer": "Illustrator", "explanation": "Adobe Illustrator is standard for vectors."},
        {"question": "What is 'White Space'?", "options": ["Empty space around elements", "The color white", "A mistake", "Low resolution"], "answer": "Empty space around elements", "explanation": "It improves readability and balance."},
        {"question": "Colors opposite each other on the color wheel are?", "options": ["Analogous", "Complementary", "Monochromatic", "Triadic"], "answer": "Complementary", "explanation": "They create high contrast."},
        {"question": "What is 'Kerning'?", "options": ["Space between lines", "Space between characters", "Font size", "Bold text"], "answer": "Space between characters", "explanation": "Adjusting space between individual letters."},
        {"question": "Which is a 'Serif' font?", "options": ["Arial", "Times New Roman", "Helvetica", "Roboto"], "answer": "Times New Roman", "explanation": "Serif fonts have small strokes at the ends of letters."},
        {"question": "What is a 'Logo'?", "options": ["A slogan", "A visual symbol for a brand", "A website", "A product"], "answer": "A visual symbol for a brand", "explanation": "Logos identify a company or product."}
    ],
    "Teacher": [
        {"question": "What is 'Pedagogy'?", "options": ["Child psychology", "Method and practice of teaching", "School administration", "Curriculum design"], "answer": "Method and practice of teaching", "explanation": "Pedagogy is the art/science of teaching."},
        {"question": "Which is an example of 'Formative Assessment'?", "options": ["Final Exam", "Standardized Test", "Classroom Quiz", "College Entrance Exam"], "answer": "Classroom Quiz", "explanation": "Formative assessments monitor learning during the process."},
        {"question": "What is 'Differentiation' in a classroom?", "options": ["Teaching everyone the same way", "Tailoring instruction to student needs", "Separating students", "Grading differently"], "answer": "Tailoring instruction to student needs", "explanation": "Adapting content for diverse learners."},
        {"question": "Who developed the theory of 'Multiple Intelligences'?", "options": ["Jean Piaget", "Howard Gardner", "B.F. Skinner", "Maria Montessori"], "answer": "Howard Gardner", "explanation": "He proposed 8 distinctive intelligences."},
        {"question": "What is 'Classroom Management'?", "options": ["Cleaning the room", "Managing student behavior and learning", "Grading papers", "Meeting parents"], "answer": "Managing student behavior and learning", "explanation": "Strategies to ensure a productive environment."},
        {"question": "Which act guarantees education in India?", "options": ["RTE Act", "RTI Act", "Consumer Act", "Labor Act"], "answer": "RTE Act", "explanation": "Right to Education Act 2009."},
        {"question": "What is a 'Lesson Plan'?", "options": ["A textbook", "A teacher's roadmap for a class", "A student's schedule", "A report card"], "answer": "A teacher's roadmap for a class", "explanation": "It details what will be taught and how."},
        {"question": "What does 'STEM' stand for?", "options": ["Science, Technology, Engineering, Math", "Sports, Teaching, English, Music", "Social Studies, Tech, Eco, Math", "Science, Tests, Exams, Marks"], "answer": "Science, Technology, Engineering, Math", "explanation": "An integrated approach to these subjects."},
        {"question": "What is 'Inclusive Education'?", "options": ["Private schools", "Educating all students together", "Online learning", "Home schooling"], "answer": "Educating all students together", "explanation": "Includes students with disabilities in mainstream classes."},
        {"question": "Bloom's Taxonomy relates to?", "options": ["Plant biology", "Levels of cognitive learning", "School budget", "Physical education"], "answer": "Levels of cognitive learning", "explanation": "A hierarchy of educational goals."}
    ],
    "Robotics Engineer": [
        {"question": "What is a 'Sensor'?", "options": ["A motor", "A device detecting changes in environment", "A computer chip", "A battery"], "answer": "A device detecting changes in environment", "explanation": "Sensors provide data about the world."},
        {"question": "What acts as the 'Brain' of a robot?", "options": ["Actuator", "Microcontroller/Processor", "Chassis", "Sensor"], "answer": "Microcontroller/Processor", "explanation": "It processes instructions and sensor data."},
        {"question": "What is 'Kinematics'?", "options": ["Study of motion without forces", "Study of forces", "Study of electricity", "Study of materials"], "answer": "Study of motion without forces", "explanation": "Crucial for robot arm movement."},
        {"question": "Which component creates movement?", "options": ["Resistor", "Capacitor", "Actuator", "Diode"], "answer": "Actuator", "explanation": "Motors and pistons are actuators."},
        {"question": "What is 'Degrees of Freedom'?", "options": ["Temperature", "Number of movable joints/axes", "Cost of robot", "Battery life"], "answer": "Number of movable joints/axes", "explanation": "Defines the robot's flexibility."},
        {"question": "Which language is commonly used in Robotics (ROS)?", "options": ["HTML", "C++ / Python", "SQL", "Swift"], "answer": "C++ / Python", "explanation": "Standard languages for ROS (Robot Operating System)."},
        {"question": "What is an 'Autonomous' robot?", "options": ["Remote controlled", "Robot acting independently", "Broken robot", "Toy robot"], "answer": "Robot acting independently", "explanation": "It operates without human intervention."},
        {"question": "What is 'LIDAR' used for?", "options": ["Cooking", "Distance sensing and mapping", "Playing music", "Cooling"], "answer": "Distance sensing and mapping", "explanation": "Light Detection and Ranging uses lasers."},
        {"question": "Isaac Asimov created?", "options": ["The first robot", "Three Laws of Robotics", "The transistor", "The battery"], "answer": "Three Laws of Robotics", "explanation": "Famous fictional rules for robot behavior."},
        {"question": "What is 'Haptics'?", "options": ["Vision", "Sense of touch technology", "Sound", "Smell"], "answer": "Sense of touch technology", "explanation": "Feedback simulating touch."}
    ],
    "Lawyer": [
        {"question": "What is the supreme law of India?", "options": ["Penal Code", "Constitution", "Civil Code", "Labor Law"], "answer": "Constitution", "explanation": "It is the foundational legal document."},
        {"question": "Who represents the state in a criminal case?", "options": ["Defense Attorney", "Public Prosecutor", "Judge", "Clerk"], "answer": "Public Prosecutor", "explanation": "They prosecute on behalf of the government."},
        {"question": "What does 'Plaintiff' mean?", "options": ["The judge", "Person filing a lawsuit", "Person being sued", "Jury member"], "answer": "Person filing a lawsuit", "explanation": "The party initiating a civil case."},
        {"question": "What is 'Habeas Corpus'?", "options": ["A writ to produce a detainee", "A dead body", "A contract", "A fine"], "answer": "A writ to produce a detainee", "explanation": "Protects against unlawful detention."},
        {"question": "What is 'IPR'?", "options": ["Indian Penal Rule", "Intellectual Property Rights", "International Police Rule", "Indian Public Rights"], "answer": "Intellectual Property Rights", "explanation": "Rights over creations of the mind."},
        {"question": "The 'Bar Council' regulates?", "options": ["Doctors", "Engineers", "Legal Practice", "Teachers"], "answer": "Legal Practice", "explanation": "It sets standards for lawyers."},
        {"question": "What is a 'Tort'?", "options": ["A cake", "A civil wrong causing harm", "A criminal act", "A contract"], "answer": "A civil wrong causing harm", "explanation": "Grounds for a lawsuit for damages."},
        {"question": "What does 'Pro Bono' mean?", "options": ["Professional", "For the public good (free legal work)", "Private", "Expensive"], "answer": "For the public good (free legal work)", "explanation": "Legal services provided for free."},
        {"question": "What is 'Perjury'?", "options": ["Stealing", "Lying under oath", "Fighting", "Arguing"], "answer": "Lying under oath", "explanation": "A serious offense in court."},
        {"question": "Who decides the verdict in a jury trial?", "options": ["The Judge", "The Jury", "The Lawyer", "The Police"], "answer": "The Jury", "explanation": "A group of citizens decides facts (less common in India now)."}
    ],
    "Athlete / Sports Coach": [
        {"question": "What is 'Aerobic' exercise?", "options": ["Weight lifting", "Sprinting", "Endurance activity with oxygen", "Stretching"], "answer": "Endurance activity with oxygen", "explanation": "Cardio exercises like running."},
        {"question": "What nutrient is key for muscle repair?", "options": ["Carbs", "Fats", "Protein", "Vitamins"], "answer": "Protein", "explanation": "Essential for building and repairing tissue."},
        {"question": "What is 'Sports Psychology'?", "options": ["Treating injuries", "Mental aspect of performance", "Designing jersey", "Scheduling games"], "answer": "Mental aspect of performance", "explanation": "Focuses on motivation and focus."},
        {"question": "The Olympics occur every?", "options": ["2 years", "4 years", "1 year", "5 years"], "answer": "4 years", "explanation": "Summer and Winter Olympics cycle."},
        {"question": "What is 'Doping'?", "options": ["Training hard", "Using banned performance drugs", "Eating healthy", "Sleeping"], "answer": "Using banned performance drugs", "explanation": "Illegal in professional sports."},
        {"question": "What does 'BMI' stand for?", "options": ["Body Mass Index", "Big Muscle Indicator", "Body Metabolic Index", "Basic Muscle Info"], "answer": "Body Mass Index", "explanation": "Measure of body fat based on weight/height."},
        {"question": "In cricket, how many players are on one team?", "options": ["9", "10", "11", "12"], "answer": "11", "explanation": "Standard playing XI."},
        {"question": "What connects muscle to bone?", "options": ["Ligament", "Tendon", "Cartilage", "Skin"], "answer": "Tendon", "explanation": "Tendons transmit force for movement."},
        {"question": "What is 'Hydration'?", "options": ["Eating food", "Maintaining fluid balance", "Sleeping", "Running"], "answer": "Maintaining fluid balance", "explanation": "Crucial for physical performance."},
        {"question": "Who is Usain Bolt?", "options": ["Swimmer", "Sprinter", "Boxer", "Gymnast"], "answer": "Sprinter", "explanation": "World record holder in 100m/200m."}
    ],
    "Economist": [
        {"question": "What is 'GDP'?", "options": ["Gross Domestic Product", "General Domestic Price", "Government Dollar Plan", "Global Daily Production"], "answer": "Gross Domestic Product", "explanation": "Total value of goods/services produced."},
        {"question": "What happens when demand exceeds supply?", "options": ["Price acts unaffected", "Price falls", "Price rises", "Production stops"], "answer": "Price rises", "explanation": "Scarcity drives prices up."},
        {"question": "Who is the 'Father of Economics'?", "options": ["Keynes", "Adam Smith", "Marx", "Friedman"], "answer": "Adam Smith", "explanation": "Author of 'The Wealth of Nations'."},
        {"question": "What is 'Inflation'?", "options": ["Falling prices", "Rising general price level", "Stable prices", "More jobs"], "answer": "Rising general price level", "explanation": "Purchasing power decreases."},
        {"question": "What represents the cost of borrowing money?", "options": ["Tax", "Interest Rate", "Inflation", "Wage"], "answer": "Interest Rate", "explanation": "Price paid for using someone else's money."},
        {"question": "What is a 'Monopoly'?", "options": ["Many sellers", "No sellers", "Single seller", "Two sellers"], "answer": "Single seller", "explanation": "One entity controls the market."},
        {"question": "What is 'Microeconomics'?", "options": ["Study of national economy", "Study of individual units/markets", "Study of money", "Study of trade"], "answer": "Study of individual units/markets", "explanation": "Focuses on firms and households."},
        {"question": "What is 'Fiscal Policy'?", "options": ["Bank rules", "Government spending and tax", "Company rules", "Stock market"], "answer": "Government spending and tax", "explanation": "Used by govts to influence economy."},
        {"question": "What is a 'Recession'?", "options": ["Economic growth", "Economic decline", "Stable economy", "High employment"], "answer": "Economic decline", "explanation": "Significant decline in activity."},
        {"question": "The 'Invisible Hand' refers to?", "options": ["Government control", "Free market self-regulation", "Thieves", "Magic"], "answer": "Free market self-regulation", "explanation": "Concept by Adam Smith."}
    ],
    "Organic Farmer": [
        {"question": "What distinguishes organic farming?", "options": ["Using machines", "No synthetic chemicals/GMOs", "Growing at night", "Using only water"], "answer": "No synthetic chemicals/GMOs", "explanation": "Relies on natural processes."},
        {"question": "What is 'Compost'?", "options": ["Plastic waste", "Decayed organic matter", "Chemical fertilizer", "Sand"], "answer": "Decayed organic matter", "explanation": "Natural fertilizer from waste."},
        {"question": "What is 'Crop Rotation'?", "options": ["Spinning crops", "Growing different crops sequentially", "Growing same crop always", "Harvesting"], "answer": "Growing different crops sequentially", "explanation": "Maintains soil health."},
        {"question": "Why use 'Cover Crops'?", "options": ["To hide the soil", "Prevent erosion and improve soil", "To make money", "To look good"], "answer": "Prevent erosion and improve soil", "explanation": "Adds nutrients and structure."},
        {"question": "What is a natural pesticide?", "options": ["DDT", "Neem Oil", "Roundup", "Arsenic"], "answer": "Neem Oil", "explanation": "Derived from Neem tree."},
        {"question": "What does GMO stand for?", "options": ["Genetically Modified Organism", "General Market Organic", "Green Moss Organism", "Growth Made Outlook"], "answer": "Genetically Modified Organism", "explanation": "Organisms with altered DNA."},
        {"question": "Who is an unlikely friend of the farmer?", "options": ["Locust", "Earthworm", "Rat", "Crow"], "answer": "Earthworm", "explanation": "They aerate soil and make compost."},
        {"question": "What is 'Permaculture'?", "options": ["Temporary farming", "Sustainable design system", "Using chemicals", "Industrial farming"], "answer": "Sustainable design system", "explanation": "Mimics natural ecosystems."},
        {"question": "What is 'Mulching'?", "options": ["Watering", "Covering soil surface", "Digging", "Planting"], "answer": "Covering soil surface", "explanation": "Retains moisture and suppresses weeds."},
        {"question": "Organic certification verifies?", "options": ["Taste", "Adherence to organic standards", "Price", "Color"], "answer": "Adherence to organic standards", "explanation": "Ensures integrity."}
    ],
    "Financial Advisor": [
        {"question": "What is 'Asset Allocation'?", "options": ["Spending money", "Dividing investments across asset classes", "Buying a house", "Paying taxes"], "answer": "Dividing investments across asset classes", "explanation": "Balances risk and reward."},
        {"question": "What implies lower risk?", "options": ["Stocks", "Crypto", "Government Bonds", "Startups"], "answer": "Government Bonds", "explanation": "Generally backed by government."},
        {"question": "What is 'Compound Interest'?", "options": ["Interest on principal only", "Interest on interest", "Bank fees", "Loan payment"], "answer": "Interest on interest", "explanation": "Growth on accumulated interest."},
        {"question": "What is a 'Mutual Fund'?", "options": ["A charity", "Pooled money managed by pros", "A loan", "A bank"], "answer": "Pooled money managed by pros", "explanation": "Diversified investment vehicle."},
        {"question": "What is a 'Bear Market'?", "options": ["Prices rising", "Prices falling", "Stable market", "Zoo market"], "answer": "Prices falling", "explanation": "Pessimistic market trend."},
        {"question": "What is 'Diversification'?", "options": ["Putting eggs in one basket", "Spreading investments", "Buying only gold", "Saving cash"], "answer": "Spreading investments", "explanation": "Reduces portfolio risk."},
        {"question": "What is 'Inflation Risk'?", "options": ["Losing money", "Purchasing power erosion", "Market crash", "Fraud"], "answer": "Purchasing power erosion", "explanation": "Money buys less over time."},
        {"question": "What is a 'Stock'?", "options": ["A loan", "Ownership share in a company", "A bond", "A sock"], "answer": "Ownership share in a company", "explanation": "Equity investment."},
        {"question": "What is 'Liquidity'?", "options": ["Water", "Ease of converting asset to cash", "Debt", "Profit"], "answer": "Ease of converting asset to cash", "explanation": "Cash is most liquid."},
        {"question": "What is a 'Dividend'?", "options": ["A tax", "Profit share paid to shareholders", "A fee", "A bill"], "answer": "Profit share paid to shareholders", "explanation": "Income from stocks."}
    ],
    "Photo Journalist": [
        {"question": "What is the 'Rule of Thirds'?", "options": ["Take 3 photos", "Composition guideline", "3 cameras", "Edit 3 times"], "answer": "Composition guideline", "explanation": "Aligning subject on grid lines."},
        {"question": "What does 'ISO' control?", "options": ["Color", "Sensor sensitivity to light", "Focus", "Zoom"], "answer": "Sensor sensitivity to light", "explanation": "Higher ISO for low light."},
        {"question": "What implies 'Candid' photography?", "options": ["Posed", "Unposed/Natural", "Studio", "Selfie"], "answer": "Unposed/Natural", "explanation": "Capturing moments as they happen."},
        {"question": "What is 'Shutter Speed'?", "options": ["Camera weight", "Duration shutter is open", "Lens size", "Flash brightness"], "answer": "Duration shutter is open", "explanation": "Controls motion blur/freeze."},
        {"question": "What is 'Ethics' in photojournalism?", "options": ["Editing photos fake", "Truth and accuracy", "Selling photos", "Using filters"], "answer": "Truth and accuracy", "explanation": "Not altering reality."},
        {"question": "What is 'Bokeh'?", "options": ["A flower", "Blurry background quality", "A lens", "A camera brand"], "answer": "Blurry background quality", "explanation": "Aesthetic out-of-focus blur."},
        {"question": "Which format is best for editing?", "options": ["JPEG", "RAW", "GIF", "PNG"], "answer": "RAW", "explanation": "Contains uncompressed data."},
        {"question": "What is a 'Caption'?", "options": ["A hat", "Text describing the photo", "A filter", "A lens cap"], "answer": "Text describing the photo", "explanation": "Provides context to news photos."},
        {"question": "Who works in a 'Darkroom'?", "options": ["Digital photographer", "Film photographer", "Web designer", "Painter"], "answer": "Film photographer", "explanation": "Developing film photos."},
        {"question": "What is 'Aperture'?", "options": ["Lens opening size", "Camera strap", "Memory card", "Battery"], "answer": "Lens opening size", "explanation": "Controls depth of field."}
    ],
    "Professor": [
        {"question": "What is a 'PhD'?", "options": ["Pharmacy degree", "Doctor of Philosophy", "Public Health", "Physical Design"], "answer": "Doctor of Philosophy", "explanation": "Highest academic degree."},
        {"question": "What is 'Tenure'?", "options": ["A salary", "Permanent job status", "A classroom", "A vacation"], "answer": "Permanent job status", "explanation": "Protects academic freedom."},
        {"question": "What is a 'Thesis'?", "options": ["A theory", "A research dissertation", "A test", "A book"], "answer": "A research dissertation", "explanation": "Final project for a degree."},
        {"question": "What means 'Peer Review'?", "options": ["Review by friends", "Evaluation by experts in field", "Review by students", "Self review"], "answer": "Evaluation by experts in field", "explanation": "Quality control for research."},
        {"question": "What is a 'Syllabus'?", "options": ["A bus", "Course outline", "A degree", "A lecture"], "answer": "Course outline", "explanation": "Plan for the course."},
        {"question": "What is 'Grant Writing'?", "options": ["Writing stories", "Applying for research funding", "Writing letters", "Grading"], "answer": "Applying for research funding", "explanation": "Crucial for research support."},
        {"question": "What implies 'Alumni'?", "options": ["Current students", "Former students/Graduates", "Teachers", "Deans"], "answer": "Former students/Graduates", "explanation": "Graduates of an institution."},
        {"question": "What is a 'Lecture'?", "options": ["A punishment", "Oral presentation", "A book", "A test"], "answer": "Oral presentation", "explanation": "Teaching method."},
        {"question": "What is 'Sabbatical'?", "options": ["A holiday", "Leave for research/study", "Firing", "Promotion"], "answer": "Leave for research/study", "explanation": "Break from teaching duties."},
        {"question": "What serves as 'Citation'?", "options": ["A fine", "Referencing a source", "A wall", "A building"], "answer": "Referencing a source", "explanation": "Crediting others' work."}
    ],
    "Entrepreneur": [
        {"question": "What is a 'Startup'?", "options": ["Old company", "New venture searching for model", "Government office", "A bank"], "answer": "New venture searching for model", "explanation": "High growth potential company."},
        {"question": "What is 'VC'?", "options": ["Video Call", "Venture Capital", "Very Cool", "Virtual Cash"], "answer": "Venture Capital", "explanation": "Funding for startups."},
        {"question": "What is a 'Pitch Deck'?", "options": ["Card game", "Presentation for investors", "A boat", "A roof"], "answer": "Presentation for investors", "explanation": "Slides explaining the business."},
        {"question": "What means 'Bootstrapping'?", "options": ["Wearing boots", "Self-funding", "Getting a loan", "Closing down"], "answer": "Self-funding", "explanation": "Building without external money."},
        {"question": "What is 'MVP'?", "options": ["Most Valuable Player", "Minimum Viable Product", "Maximum Visual Power", "Mini Video Player"], "answer": "Minimum Viable Product", "explanation": "Basic version to test market."},
        {"question": "What is 'Equity'?", "options": ["Fairness", "Ownership stake", "Debt", "Cash"], "answer": "Ownership stake", "explanation": "Share of the company."},
        {"question": "What is a 'Unicorn'?", "options": ["Mythical horse", "Startup valued over $1 Billion", "Failed startup", "Small business"], "answer": "Startup valued over $1 Billion", "explanation": "Rare success."},
        {"question": "What is 'ROI'?", "options": ["Rate of Interest", "Return on Investment", "Rule of Internet", "Risk on Income"], "answer": "Return on Investment", "explanation": "Measure of profitability."},
        {"question": "What is a 'Pivot'?", "options": ["Dancing", "Changing business strategy", "Quitting", "Hiring"], "answer": "Changing business strategy", "explanation": "Shift in direction."},
        {"question": "Who is an 'Angel Investor'?", "options": ["A religious figure", "Individual investing personal funds", "A bank", "The government"], "answer": "Individual investing personal funds", "explanation": "Early stage investor."}
    ],
    "Civil Servant (IAS/IPS)": [
        {"question": "Who recruits IAS officers?", "options": ["SSC", "UPSC", "IBPS", "NTA"], "answer": "UPSC", "explanation": "Union Public Service Commission."},
        {"question": "What is the role of a 'District Magistrate'?", "options": ["Judge", "Head of District Administration", "Doctor", "Teacher"], "answer": "Head of District Administration", "explanation": "Key administrative role."},
        {"question": "The 'Iron Frame of India' refers to?", "options": ["Railways", "Civil Services", "Army", "Roads"], "answer": "Civil Services", "explanation": "Term by Vallabhbhai Patel."},
        {"question": "Where is LBSNAA?", "options": ["Delhi", "Mussoorie", "Hyderabad", "Bangalore"], "answer": "Mussoorie", "explanation": "IAS training academy."},
        {"question": "Who is the head of Indian Police?", "options": ["DGP", "IG", "SP", "Constable"], "answer": "DGP", "explanation": "Director General of Police."},
        {"question": "IFS stands for?", "options": ["Indian Forest Service", "Indian Foreign Service", "Both (Context dependent)", "None"], "answer": "Both (Context dependent)", "explanation": "Can be Foreign or Forest."},
        {"question": "What implies 'Diplomacy'?", "options": ["Fighting", "Managing international relations", "Teaching", "Farming"], "answer": "Managing international relations", "explanation": "Key role of IFS."},
        {"question": "What is a 'Bureaucrat'?", "options": ["Politician", "Government official", "Judge", "Soldier"], "answer": "Government official", "explanation": "Member of bureaucracy."},
        {"question": "The 'Cabinet Secretary' is?", "options": ["A minister", "Highest civil servant", "A clerk", "A typist"], "answer": "Highest civil servant", "explanation": "Topmost executive official."},
        {"question": "Civil servants must remain?", "options": ["Partisan", "Politically Neutral", "Active in politics", "Lazy"], "answer": "Politically Neutral", "explanation": "Serve the government of the day."}
    ],
    "Politician": [
        {"question": "What is the lower house of Parliament?", "options": ["Rajya Sabha", "Lok Sabha", "Vidhan Sabha", "White House"], "answer": "Lok Sabha", "explanation": "House of the People."},
        {"question": "Who explains the Constitution?", "options": ["President", "Supreme Court", "PM", "Governor"], "answer": "Supreme Court", "explanation": "Final interpreter."},
        {"question": "What is 'Universal Adult Franchise'?", "options": ["Right to business", "Right to vote for all adults", "Right to travel", "Right to eat"], "answer": "Right to vote for all adults", "explanation": "Voting right > 18 years."},
        {"question": "Who is the Head of State in India?", "options": ["Prime Minister", "President", "Chief Justice", "Speaker"], "answer": "President", "explanation": "Ceremonial head."},
        {"question": "What is a 'Constituency'?", "options": ["A law", "Area represented by an elected official", "A party", "A voting machine"], "answer": "Area represented by an elected official", "explanation": "Electoral division."},
        {"question": "What is a 'Manifesto'?", "options": ["A person", "Declaration of party policy", "A rally", "A vote"], "answer": "Declaration of party policy", "explanation": "Promises made before election."},
        {"question": "What represents the 'Fourth Estate'?", "options": ["Legislature", "Executive", "Judiciary", "Media/Press"], "answer": "Media/Press", "explanation": "Watchdog of democracy."},
        {"question": "What is 'Democracy'?", "options": ["Rule by King", "Rule by People", "Rule by Army", "Rule by Wealthy"], "answer": "Rule by People", "explanation": "Of, by, and for the people."},
        {"question": "The minimum age to be MP (Lok Sabha)?", "options": ["18", "21", "25", "30"], "answer": "25", "explanation": "Constitutional requirement."},
        {"question": "What is a 'Coalition Government'?", "options": ["Single party rule", "Alliance of parties", "Military rule", "No government"], "answer": "Alliance of parties", "explanation": "When no single party has majority."}
    ]
}
